// Generated by 'unplugin-auto-import'
export {}
declare global {
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
}
